### ISSUE TITLE
缺失esp_heap_alloc_caps.h

### ISSUE THREAD

**Issue by erikaemma** [kylefjl/HoloCubic_AIO_TOMATO#2]
src/app/media_player/DMADrawer.cpp:13:10: fatal error: esp_heap_alloc_caps.h: No such file or directory

我编译原版和AIO原版都成功了，但是此项目未成功

**Comment by kylefjl** [comment]
不好意思，一直没注意看消息，现在我已经把最新的AIO移植过来了，这个问题已经解决了，也完善了一下代码和readme
