### ISSUE TITLE
还是会报错

### ISSUE THREAD

**Issue by huasyuan** [kylefjl/HoloCubic_AIO_TOMATO#3]
你好，我将您写的代码app/tomato完整复制到了https://github.com/ClimbSnail/HoloCubic_AIO最新的里面
而且HoloCubic_AIO.cpp也将tomoto相关代码写了进去
但编译还是会出错。
所以在这里恳请大佬您，重写一次，符合https://github.com/ClimbSnail/HoloCubic_AIO最新的
比如AIO最新的app注册代码已经没用#endif了，而您的代码里面还有#endif
 // 将APP"安装"到controller里
#if APP_WEATHER_USE
    app_controller->app_install(&weather_app);
#endif
就像这样

**Comment by kylefjl** [comment]
你好，我刚刚看了一下最新的HoloCubic_AIO的代码，还是有#endif的，是不是你那里的版本不是最新的，这个是我看的链接：https://github.com/ClimbSnail/HoloCubic_AIO/blob/main/AIO_Firmware_PIO/src/HoloCubic_AIO.cpp，你可以再看一下，大概在135行

**Comment by kylefjl** [comment]
如果还是有问题的话可以把具体的错误信息发出来，我看看是啥原因

**Comment by huasyuan** [comment]
OK啦，没有问题，是我水平太低了，不好意思啦

**Comment by kylefjl** [comment]
没事，那我把问题关了
